version: "3.9"

services:
  hp_mariadb:
    image: mariadb:11.8
    container_name: hp_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: harryquiz
      MYSQL_USER: hpuser
      MYSQL_PASSWORD: hppassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  hp_quiz_app:
    build: .
    container_name: hp_quiz_app
    restart: always
    depends_on:
      - hp_mariadb
    ports:
      - "8000:8000"
    environment:
      DB_HOST: hp_mariadb
      DB_PORT: 3306
      DB_USER: hpuser
      DB_PASSWORD: hppassword
      DB_NAME: harryquiz
    volumes:
      - ./static/uploads:/app/static/uploads
volumes:
  db_data: