# ─────────────────────────────────────────────────────────────
# Configuración de Nginx como proxy inverso
# ─────────────────────────────────────────────────────────────

events {
    worker_connections 1024;   # Número máximo de conexiones simultáneas
}

http {
    server {
        listen 80;             # Nginx escucha en el puerto 80 (HTTP)
        server_name localhost; # Nombre del servidor (localhost sin dominio)

        # Tamaño máximo de archivo para subidas de imágenes
        client_max_body_size 10M;

        location / {
            # Redirige todas las peticiones a la app FastAPI
            proxy_pass http://hp_quiz_app:8000;

            # Cabeceras necesarias para que FastAPI reciba la información correcta
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}