# ─────────────────────────────────────────────────────────────
# Configuración de Nginx como proxy inverso
# ─────────────────────────────────────────────────────────────

events {
    worker_connections 1024;   # Número máximo de conexiones simultáneas
}

http {
    server {
        listen 80;             # Nginx escucha en el puerto 80 (dirección a la que se accede)
        server_name localhost benito-martin-oscar.proyecto-daw.iesabdera.local;

        # Tamaño máximo de archivo para subidas de imágenes 10 Megabytes
        client_max_body_size 10M;

        location / {
            # Redirige todas las peticiones a la app FastAPI
            proxy_pass http://hp_quiz_app:8000;

            # Cabeceras necesarias para que FastAPI reciba la información correcta
            proxy_set_header Host $host; # → le dice a FastAPI el dominio original de la petición
            proxy_set_header X-Real-IP $remote_addr; # → le pasa a FastAPI la IP real del usuario
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  # → lista de IPs por las que ha pasado la petición
            proxy_set_header X-Forwarded-Proto $scheme; # → le dice a FastAPI si la petición era HTTP o HTTPS
        }
    }
}

#"El nginx.conf configura Nginx como proxy inverso — 
#escucha en el puerto 80, captura todas las peticiones y las redirige a 
#FastAPI en el puerto 8000. Las cabeceras proxy_set_header pasan a FastAPI información sobre la petición original como la IP del usuario."
# Las cabeceras proxy_set_header

# Es como cuando el recepcionista le pasa una nota al empleado del fondo diciéndole:

# quién es el cliente (X-Real-IP)
# por dónde entró (X-Forwarded-Proto)
# a qué tienda quería ir (Host)